## -*- encoding: utf-8 -*-
# This file was *autogenerated* from the file baitap2-loigiai.sagetex.sage.
from sage.all_cmdline import *   # import sage library
_sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_7 = Integer(7); _sage_const_6 = Integer(6); _sage_const_5 = Integer(5); _sage_const_4 = Integer(4); _sage_const_9 = Integer(9); _sage_const_8 = Integer(8); _sage_const_96 = Integer(96); _sage_const_25 = Integer(25); _sage_const_46 = Integer(46); _sage_const_61 = Integer(61); _sage_const_49 = Integer(49); _sage_const_82 = Integer(82); _sage_const_171 = Integer(171); _sage_const_177 = Integer(177); _sage_const_232 = Integer(232); _sage_const_230 = Integer(230); _sage_const_274 = Integer(274); _sage_const_270 = Integer(270); _sage_const_218 = Integer(218); _sage_const_12 = Integer(12); _sage_const_11 = Integer(11); _sage_const_10 = Integer(10); _sage_const_15 = Integer(15); _sage_const_14 = Integer(14); _sage_const_57 = Integer(57); _sage_const_266 = Integer(266); _sage_const_35 = Integer(35); _sage_const_50 = Integer(50); _sage_const_166 = Integer(166); _sage_const_78 = Integer(78); _sage_const_100 = Integer(100); _sage_const_226 = Integer(226); _sage_const_222 = Integer(222)## This file (baitap2-loigiai.sagetex.sage) was *autogenerated* from baitap2-loigiai.tex with sagetex.sty version 2012/01/16 v2.3.3-69dcb0eb93de.
import sagetex
_st_ = sagetex.SageTeXProcessor('baitap2-loigiai', version='2012/01/16 v2.3.3-69dcb0eb93de', version_check=True)
_st_.blockbegin()
try:
 A=matrix([[_sage_const_10 ,-_sage_const_1 ,_sage_const_2 ,_sage_const_0 ],[-_sage_const_1 ,_sage_const_11 ,-_sage_const_1 ,_sage_const_3 ],[_sage_const_2 ,-_sage_const_1 ,_sage_const_10 ,-_sage_const_1 ],[_sage_const_0 ,_sage_const_3 ,-_sage_const_1 ,_sage_const_8 ]]);
 B=matrix([[_sage_const_6 ],[_sage_const_25 ],[-_sage_const_11 ],[_sage_const_15 ]]);
except:
 _st_.goboom(_sage_const_78 )
_st_.blockend()
try:
 _st_.inline(_sage_const_0 , latex(A))
except:
 _st_.goboom(_sage_const_82 )
try:
 _st_.inline(_sage_const_1 , latex(B))
except:
 _st_.goboom(_sage_const_96 )
_st_.blockbegin()
try:
 A=matrix([[_sage_const_1 ,_sage_const_1 ,_sage_const_1 ,_sage_const_1 ,_sage_const_6 ,_sage_const_12 ,_sage_const_1 ],[_sage_const_1 ,-_sage_const_2 ,_sage_const_0 ,_sage_const_0 ,_sage_const_0 ,_sage_const_0 ,_sage_const_0 ],[_sage_const_0 ,_sage_const_1 ,-_sage_const_2 ,_sage_const_0 ,_sage_const_0 ,_sage_const_0 ,_sage_const_0 ],[_sage_const_0 ,_sage_const_0 ,_sage_const_1 ,-_sage_const_1 ,-_sage_const_2 ,-_sage_const_2 ,-_sage_const_1 ],[_sage_const_0 ,_sage_const_0 ,_sage_const_0 ,_sage_const_1 ,-_sage_const_2 ,-_sage_const_4 ,_sage_const_0 ],[_sage_const_0 ,_sage_const_0 ,_sage_const_0 ,_sage_const_0 ,_sage_const_1 ,-_sage_const_3 /_sage_const_2 ,_sage_const_0 ],[_sage_const_0 ,_sage_const_0 ,_sage_const_0 ,_sage_const_0 ,_sage_const_0 ,_sage_const_1 ,-_sage_const_2 ]]);
 B=matrix([[_sage_const_232 ],[_sage_const_0 ],[_sage_const_0 ],[_sage_const_0 ],[_sage_const_0 ],[_sage_const_0 ],[_sage_const_0 ]]);
 X=matrix([_sage_const_100 ,_sage_const_50 ,_sage_const_25 ,_sage_const_14 ,_sage_const_3 ,_sage_const_2 ,_sage_const_1 ]);
except:
 _st_.goboom(_sage_const_166 )
_st_.blockend()
try:
 _st_.inline(_sage_const_2 , latex(A))
except:
 _st_.goboom(_sage_const_171 )
try:
 _st_.inline(_sage_const_3 , latex(B))
except:
 _st_.goboom(_sage_const_171 )
try:
 _st_.inline(_sage_const_4 , latex(X.transpose()))
except:
 _st_.goboom(_sage_const_177 )
_st_.blockbegin()
try:
 X1=matrix([_sage_const_1 ,_sage_const_1 ,_sage_const_2 ]);
 X2=matrix([_sage_const_1 ,_sage_const_1 ,_sage_const_1 ]);
 X3=matrix([-_sage_const_1 ,_sage_const_3 ,_sage_const_2 ]);
except:
 _st_.goboom(_sage_const_218 )
_st_.blockend()
try:
 _st_.inline(_sage_const_5 , latex(X1.transpose()))
except:
 _st_.goboom(_sage_const_222 )
try:
 _st_.inline(_sage_const_6 , latex(X2.transpose()))
except:
 _st_.goboom(_sage_const_226 )
try:
 _st_.inline(_sage_const_7 , latex(X3.transpose()))
except:
 _st_.goboom(_sage_const_230 )
_st_.blockbegin()
try:
 A1=matrix([[_sage_const_1 ,-_sage_const_8 ,-_sage_const_2 ,_sage_const_1 ],[_sage_const_1 ,_sage_const_1 ,_sage_const_5 ,_sage_const_4 ],[_sage_const_3 ,-_sage_const_1 ,_sage_const_1 ,-_sage_const_2 ]])
 X1=matrix([[-_sage_const_61 /_sage_const_49 ,-_sage_const_4 /_sage_const_7 ,_sage_const_57 /_sage_const_49 ]])
 A2=matrix([[_sage_const_1 ,_sage_const_4 ,_sage_const_0 ,_sage_const_5 ],[_sage_const_0 ,_sage_const_1 ,_sage_const_2 ,_sage_const_2 ],[_sage_const_4 ,_sage_const_0 ,_sage_const_3 ,_sage_const_0 ]])
 X2=matrix([[-_sage_const_9 /_sage_const_35 ,_sage_const_46 /_sage_const_35 ,_sage_const_12 /_sage_const_35 ]])
except:
 _st_.goboom(_sage_const_266 )
_st_.blockend()
try:
 _st_.inline(_sage_const_8 , latex(X1.transpose()))
except:
 _st_.goboom(_sage_const_270 )
try:
 _st_.inline(_sage_const_9 , latex(X2.transpose()))
except:
 _st_.goboom(_sage_const_274 )
_st_.endofdoc()
