## -*- encoding: utf-8 -*-
# This file was *autogenerated* from the file baitap2.sagetex.sage.
from sage.all_cmdline import *   # import sage library
_sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_6 = Integer(6); _sage_const_8 = Integer(8); _sage_const_77 = Integer(77); _sage_const_95 = Integer(95); _sage_const_81 = Integer(81); _sage_const_11 = Integer(11); _sage_const_10 = Integer(10); _sage_const_15 = Integer(15); _sage_const_25 = Integer(25)## This file (baitap2.sagetex.sage) was *autogenerated* from baitap2.tex with sagetex.sty version 2012/01/16 v2.3.3-69dcb0eb93de.
import sagetex
_st_ = sagetex.SageTeXProcessor('baitap2', version='2012/01/16 v2.3.3-69dcb0eb93de', version_check=True)
_st_.blockbegin()
try:
 A=matrix([[_sage_const_10 ,-_sage_const_1 ,_sage_const_2 ,_sage_const_0 ],[-_sage_const_1 ,_sage_const_11 ,-_sage_const_1 ,_sage_const_3 ],[_sage_const_2 ,-_sage_const_1 ,_sage_const_10 ,-_sage_const_1 ],[_sage_const_0 ,_sage_const_3 ,-_sage_const_1 ,_sage_const_8 ]]);
 B=matrix([[_sage_const_6 ],[_sage_const_25 ],[-_sage_const_11 ],[_sage_const_15 ]]);
except:
 _st_.goboom(_sage_const_77 )
_st_.blockend()
try:
 _st_.inline(_sage_const_0 , latex(A))
except:
 _st_.goboom(_sage_const_81 )
try:
 _st_.inline(_sage_const_1 , latex(B))
except:
 _st_.goboom(_sage_const_95 )
_st_.endofdoc()
