## -*- encoding: utf-8 -*-
## This file (baitap3.sagetex.sage) was *autogenerated* from baitap3.tex with sagetex.sty version 2012/01/16 v2.3.3-69dcb0eb93de.
import sagetex
_st_ = sagetex.SageTeXProcessor('baitap3', version='2012/01/16 v2.3.3-69dcb0eb93de', version_check=True)
_st_.endofdoc()
