## -*- encoding: utf-8 -*-
# This file was *autogenerated* from the file thicuoiky2.sagetex.sage.
from sage.all_cmdline import *   # import sage library
_sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_5 = Integer(5); _sage_const_4 = Integer(4); _sage_const_261 = Integer(261); _sage_const_266 = Integer(266); _sage_const_0p6058 = RealNumber('0.6058'); _sage_const_88 = Integer(88); _sage_const_2p1542 = RealNumber('2.1542'); _sage_const_0p189 = RealNumber('0.189'); _sage_const_84 = Integer(84); _sage_const_86 = Integer(86); _sage_const_0p9755 = RealNumber('0.9755'); _sage_const_0p1 = RealNumber('0.1'); _sage_const_0p2 = RealNumber('0.2'); _sage_const_255 = Integer(255); _sage_const_0p1863 = RealNumber('0.1863'); _sage_const_1p5224 = RealNumber('1.5224'); _sage_const_0p1929 = RealNumber('0.1929'); _sage_const_10 = Integer(10); _sage_const_9p81 = RealNumber('9.81'); _sage_const_50 = Integer(50); _sage_const_2p8829 = RealNumber('2.8829'); _sage_const_169 = Integer(169); _sage_const_0p0039 = RealNumber('0.0039')## This file (thicuoiky2.sagetex.sage) was *autogenerated* from thicuoiky2.tex with sagetex.sty version 2012/01/16 v2.3.3-69dcb0eb93de.
import sagetex
_st_ = sagetex.SageTeXProcessor('thicuoiky2', version='2012/01/16 v2.3.3-69dcb0eb93de', version_check=True)
_st_.blockbegin()
try:
  __tmp__=var("x"); f4 = symbolic_expression((x+_sage_const_2 /_sage_const_3 )**_sage_const_2 *(x-_sage_const_4 /_sage_const_3 )).function(x)
  x0=_sage_const_1 
  f4diff=diff(f4,x)
  __tmp__=var("x"); g1 = symbolic_expression((x**_sage_const_3 -f4(x))**(_sage_const_1 /_sage_const_3 )).function(x)
  g1=g1.expand()
  g1diff=diff(g1,x)
  g1diff2=diff(g1,x,_sage_const_2 )
except:
 _st_.goboom(_sage_const_84 )
_st_.blockend()
try:
 _st_.inline(_sage_const_0 , latex(f4(x).expand()))
except:
 _st_.goboom(_sage_const_86 )
try:
 _st_.inline(_sage_const_1 , latex(x0))
except:
 _st_.goboom(_sage_const_88 )
_st_.blockbegin()
try:
 latex.matrix_delimiters("[", "]")
 A=matrix([[_sage_const_3 ,_sage_const_1 ,-_sage_const_1 ],[_sage_const_1 ,_sage_const_4 ,_sage_const_1 ],[_sage_const_1 ,-_sage_const_2 ,-_sage_const_5 ]])
 A_rdf=matrix(RDF,[[_sage_const_3 ,_sage_const_1 ,-_sage_const_1 ],[_sage_const_1 ,_sage_const_4 ,_sage_const_1 ],[_sage_const_1 ,-_sage_const_2 ,-_sage_const_5 ]]) # lệnh tính condition() chỉ có với ma trận real-double-float, nhưng dùng ma trận RDF thì lại không giải được phương trình bằng kiểu lệnh A\B hoặc A.solve_right(B). Sẽ fix sau.
 B=matrix([[_sage_const_5 ],[_sage_const_4 ],[_sage_const_4 ]])
 x,y,z=var('x y z')
 X=matrix([[x],[y],[z]])
 Xp=A * BackslashOperator() * B
 #Xp=[1,2,3]
 kA1=A_rdf.condition(_sage_const_1 )
 kAinf=A_rdf.condition(infinity)
except:
 _st_.goboom(_sage_const_169 )
_st_.blockend()
_st_.blockbegin()
try:
 n=_sage_const_10 
 tkx=[_sage_const_0p1 *i for i in range(n+_sage_const_1 )]
 tk=[_sage_const_0p1 *i for i in range(n)]
 v0=-_sage_const_2 
 g=_sage_const_9p81 
 vt=[v0+g*tkx[i] for i in range(n+_sage_const_1 )]
 xt=[_sage_const_0  for i in range(n+_sage_const_1 )]
 for i in range(n):
  xt[i+_sage_const_1 ]=xt[i]+(vt[i+_sage_const_1 ]+vt[i])*_sage_const_0p1 /_sage_const_2 
 # Dữ liệu có sai số ngẫu nhiên
 xk=[_sage_const_0 ,-_sage_const_0p2 ,-_sage_const_0p189 ,-_sage_const_0p1929 ,_sage_const_0p0039 ,_sage_const_0p1863 ,_sage_const_0p6058 ,_sage_const_0p9755 ,_sage_const_1p5224 ,_sage_const_2p1542 ,_sage_const_2p8829 ]
 #xk=[0 for i in range(n+1)]
 #for i in range(n):
 # xk[i+1]=xt[i]+(vt[i+1]+vt[i])*0.1/2+(0.1*random()-0.05)
 # Dữ liệu chính xác
 #xk=xt
 tk2=[tk[i]**_sage_const_2  for i in range(n)]
 vk=[(xk[i+_sage_const_1 ]-xk[i])/_sage_const_0p1  for i in range(n)]
 zk=zip(tk,vk)
 plotdata=list_plot(zk, size=_sage_const_50 , legend_label='($t_k$,$v_k$)')
 matA=matrix([[n,sum(tk)],[sum(tk),sum(tk2)]])
 tkvk=[tk[i]*vk[i] for i in range(n)]
 matB=vector([sum(vk),sum(tkvk)])
 a,b=N(matA * BackslashOperator() * matB)
 t=var('t')
 hamxapxi=round(a,_sage_const_3 )+round(b,_sage_const_3 )*t
 plotline=plot(hamxapxi,_sage_const_0 ,tkx[n], color='red', legend_label='($y=A+Bt$)')
 
 tableVD5=r"\begin{tabular}{l|c|l}"
 tableVD5+=r"$k$ & $t_k$ & $v_k$ \\ \hline"
 for i in range(n):
   tableVD5+=latex(i) + r"&" + latex(round(tk[i],_sage_const_1 )) + r"&" + latex(round(vk[i],_sage_const_3 )) + r"\\"
 tableVD5+=r"\end{tabular}"
 
 tableTXk=r"\begin{tabular}{l|c|l}"
 tableTXk+=r"$k$ & $t_k$ & $x_k$ \\ \hline"
 for i in range(n+_sage_const_1 ):
   tableTXk+=latex(i) + r"&" + latex(round(tkx[i],_sage_const_1 )) + r"&" + latex(round(xk[i],_sage_const_4 )) + r"\\"
 tableTXk+=r"\end{tabular}"
 
except:
 _st_.goboom(_sage_const_255 )
_st_.blockend()
try:
 _st_.inline(_sage_const_2 , latex(n-_sage_const_1 ))
except:
 _st_.goboom(_sage_const_261 )
try:
 _st_.inline(_sage_const_3 , tableTXk)
except:
 _st_.goboom(_sage_const_266 )
_st_.endofdoc()
