## -*- encoding: utf-8 -*-
# This file was *autogenerated* from the file thicuoiky1.sagetex.sage.
from sage.all_cmdline import *   # import sage library
_sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_7 = Integer(7); _sage_const_5 = Integer(5); _sage_const_4 = Integer(4); _sage_const_1p1464 = RealNumber('1.1464'); _sage_const_8 = Integer(8); _sage_const_243 = Integer(243); _sage_const_28 = Integer(28); _sage_const_24 = Integer(24); _sage_const_0p8226 = RealNumber('0.8226'); _sage_const_9p81 = RealNumber('9.81'); _sage_const_84 = Integer(84); _sage_const_80 = Integer(80); _sage_const_82 = Integer(82); _sage_const_0p1 = RealNumber('0.1'); _sage_const_156 = Integer(156); _sage_const_238 = Integer(238); _sage_const_232 = Integer(232); _sage_const_1p1031 = RealNumber('1.1031'); _sage_const_1p2813 = RealNumber('1.2813'); _sage_const_0p5209 = RealNumber('0.5209'); _sage_const_0p6008 = RealNumber('0.6008'); _sage_const_10 = Integer(10); _sage_const_1p2477 = RealNumber('1.2477'); _sage_const_32 = Integer(32); _sage_const_50 = Integer(50); _sage_const_0p1709 = RealNumber('0.1709'); _sage_const_1p309 = RealNumber('1.309'); _sage_const_161 = Integer(161); _sage_const_0p8759 = RealNumber('0.8759')## This file (thicuoiky1.sagetex.sage) was *autogenerated* from thicuoiky1.tex with sagetex.sty version 2012/01/16 v2.3.3-69dcb0eb93de.
import sagetex
_st_ = sagetex.SageTeXProcessor('thicuoiky1', version='2012/01/16 v2.3.3-69dcb0eb93de', version_check=True)
_st_.blockbegin()
try:
  __tmp__=var("x"); f4 = symbolic_expression((x-_sage_const_1 /_sage_const_3 )**_sage_const_2 *(x+_sage_const_2 /_sage_const_3 )).function(x)
  x0=_sage_const_1 
  f4diff=diff(f4,x)
except:
 _st_.goboom(_sage_const_80 )
_st_.blockend()
try:
 _st_.inline(_sage_const_0 , latex(f4(x).expand()))
except:
 _st_.goboom(_sage_const_82 )
try:
 _st_.inline(_sage_const_1 , latex(x0))
except:
 _st_.goboom(_sage_const_84 )
_st_.blockbegin()
try:
 latex.matrix_delimiters("[", "]")
 A=matrix([[_sage_const_1 ,_sage_const_5 ,_sage_const_7 ],[_sage_const_3 ,_sage_const_3 ,_sage_const_5 ],[_sage_const_2 ,_sage_const_1 ,_sage_const_8 ]])
 A_rdf=matrix(RDF,[[_sage_const_1 ,_sage_const_5 ,_sage_const_7 ],[_sage_const_3 ,_sage_const_3 ,_sage_const_5 ],[_sage_const_2 ,_sage_const_1 ,_sage_const_8 ]])
 B=matrix([[_sage_const_32 ],[_sage_const_24 ],[_sage_const_28 ]])
 Xp=A * BackslashOperator() * B
 #Xp=[1,2,3]
 kA1=A_rdf.condition(_sage_const_1 )
 kAinf=A_rdf.condition(infinity)
except:
 _st_.goboom(_sage_const_156 )
_st_.blockend()
try:
 _st_.inline(_sage_const_2 , latex(A))
except:
 _st_.goboom(_sage_const_161 )
try:
 _st_.inline(_sage_const_3 , latex(B))
except:
 _st_.goboom(_sage_const_161 )
_st_.blockbegin()
try:
 n=_sage_const_10 
 tkx=[_sage_const_0p1 *i for i in range(n+_sage_const_1 )]
 tk=[_sage_const_0p1 *i for i in range(n)]
 v0=_sage_const_5 
 g=-_sage_const_9p81 
 vt=[v0+g*tkx[i] for i in range(n+_sage_const_1 )]
 xt=[_sage_const_0  for i in range(n+_sage_const_1 )]
 for i in range(n):
  xt[i+_sage_const_1 ]=xt[i]+(vt[i+_sage_const_1 ]+vt[i])*_sage_const_0p1 /_sage_const_2 
 # Dữ liệu có sai số ngẫu nhiên
 #xk=[0.00000,0.46844,0.82762,1.14953,1.36673,1.47872,1.53896,1.41880,1.20203,0.88217,0.45938]
 xk=[_sage_const_0 ,_sage_const_0p5209 ,_sage_const_0p8226 ,_sage_const_1p1031 ,_sage_const_1p2477 ,_sage_const_1p2813 ,_sage_const_1p309 ,_sage_const_1p1464 ,_sage_const_0p8759 ,_sage_const_0p6008 ,_sage_const_0p1709 ]
 #xk=[0 for i in range(n+1)]
 #for i in range(n):
 # xk[i+1]=xt[i]+(vt[i+1]+vt[i])*0.1/2+0.1*random()
 # Dữ liệu chính xác
 #xk=xt
 tk2=[tk[i]**_sage_const_2  for i in range(n)]
 vk=[(xk[i+_sage_const_1 ]-xk[i])/_sage_const_0p1  for i in range(n)]
 zk=zip(tk,vk)
 plotdata=list_plot(zk, size=_sage_const_50 , legend_label='($t_k$,$v_k$)')
 matA=matrix([[n,sum(tk)],[sum(tk),sum(tk2)]])
 tkvk=[tk[i]*vk[i] for i in range(n)]
 matB=vector([sum(vk),sum(tkvk)])
 a,b=N(matA * BackslashOperator() * matB)
 t=var('t')
 hamxapxi=round(a,_sage_const_3 )+round(b,_sage_const_3 )*t
 plotline=plot(hamxapxi,_sage_const_0 ,tkx[n], color='red', legend_label='($y=A+Bt$)')
 
 tableVD5=r"\begin{tabular}{l|c|l}"
 tableVD5+=r"$k$ & $t_k$ & $v_k$ \\ \hline"
 for i in range(n):
   tableVD5+=latex(i) + r"&" + latex(round(tk[i],_sage_const_1 )) + r"&" + latex(round(vk[i],_sage_const_3 )) + r"\\"
 tableVD5+=r"\end{tabular}"
 
 tableTXk=r"\begin{tabular}{l|c|l}"
 tableTXk+=r"$k$ & $t_k$ & $x_k$ \\ \hline"
 for i in range(n+_sage_const_1 ):
   tableTXk+=latex(i) + r"&" + latex(round(tkx[i],_sage_const_1 )) + r"&" + latex(round(xk[i],_sage_const_4 )) + r"\\"
 tableTXk+=r"\end{tabular}"
 
except:
 _st_.goboom(_sage_const_232 )
_st_.blockend()
try:
 _st_.inline(_sage_const_4 , latex(n-_sage_const_1 ))
except:
 _st_.goboom(_sage_const_238 )
try:
 _st_.inline(_sage_const_5 , tableTXk)
except:
 _st_.goboom(_sage_const_243 )
_st_.endofdoc()
