## -*- encoding: utf-8 -*-
# This file was *autogenerated* from the file chap6.sagetex.sage.
from sage.all_cmdline import *   # import sage library
_sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_9p81 = RealNumber('9.81'); _sage_const_216 = Integer(216); _sage_const_100 = Integer(100); _sage_const_366 = Integer(366); _sage_const_0p1 = RealNumber('0.1'); _sage_const_0p2 = RealNumber('0.2'); _sage_const_229 = Integer(229); _sage_const_368 = Integer(368); _sage_const_20 = Integer(20)## This file (chap6.sagetex.sage) was *autogenerated* from chap6.tex with sagetex.sty version 2012/01/16 v2.3.3-69dcb0eb93de.
import sagetex
_st_ = sagetex.SageTeXProcessor('chap6', version='2012/01/16 v2.3.3-69dcb0eb93de', version_check=True)
_st_.blockbegin()
try:
 t,x,y=var('t','x','y')
 P=desolve_system_rk4([-x/_sage_const_2 +y,-x-y/_sage_const_2 ],[x,y],ics=[_sage_const_0 ,_sage_const_3 ,_sage_const_1 ],ivar=t,end_points=_sage_const_20 )
 XY=[ [j,k] for i,j,k in P]
 plotxy=list_plot(XY)
except:
 _st_.goboom(_sage_const_216 )
_st_.blockend()
try:
 _st_.plot(_sage_const_0 , format='notprovided', _p_=plotxy)
except:
 _st_.goboom(_sage_const_229 )
_st_.blockbegin()
try:
 g=_sage_const_9p81 
 m=_sage_const_1 
 k=_sage_const_0p2 
 kf=_sage_const_0p1 
 
 from sage.calculus.desolvers import desolve_system_rk4
 x,y,t=var('x y t')
 P=desolve_system_rk4([y,-(k/m)*x-(kf/m)*y+g],[x,y],ics=[_sage_const_0 ,_sage_const_0 ,_sage_const_0 ],ivar=t,end_points=_sage_const_100 )
 Q=[ [i,j] for i,j,k in P]
 plotmass_spring=list_plot(Q)
except:
 _st_.goboom(_sage_const_366 )
_st_.blockend()
try:
 _st_.plot(_sage_const_1 , format='notprovided', _p_=plotmass_spring)
except:
 _st_.goboom(_sage_const_368 )
_st_.endofdoc()
