test_nargin
test_nargin
test_nargin
test_nargin
clc
test_nargin
test_nargin
clc
test_nargin(1,2)
test_nargin(1,2)
test_nargin(1,2)
test_nargin(1,2)
test_nargin(1,2)
test_nargin(1,2)
test_nargin(1,2)
test_nargin(1,5)
[x,fx,n]=bisect(@hamso,1,2)
[x,fx,n]=bisect(@hamso,1,2)