## -*- encoding: utf-8 -*-
# This file was *autogenerated* from the file chap1.sagetex.sage.
from sage.all_cmdline import *   # import sage library
_sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_63 = Integer(63); _sage_const_67 = Integer(67); _sage_const_4 = Integer(4); _sage_const_1234 = Integer(1234); _sage_const_59 = Integer(59); _sage_const_74 = Integer(74); _sage_const_35 = Integer(35)## This file (chap1.sagetex.sage) was *autogenerated* from chap1.tex with sagetex.sty version 2012/01/16 v2.3.3-69dcb0eb93de.
import sagetex
_st_ = sagetex.SageTeXProcessor('chap1', version='2012/01/16 v2.3.3-69dcb0eb93de', version_check=True)
try:
 _st_.inline(_sage_const_0 , latex(number_of_partitions(_sage_const_1234 )))
except:
 _st_.goboom(_sage_const_35 )
try:
 _st_.inline(_sage_const_1 , latex(number_of_partitions(_sage_const_1234 )))
except:
 _st_.goboom(_sage_const_59 )
try:
 _st_.inline(_sage_const_2 , latex('Hello'))
except:
 _st_.goboom(_sage_const_63 )
_st_.blockbegin()
try:
     __tmp__=var("x"); f = symbolic_expression(exp(x) * sin(_sage_const_2 *x) *cos(x)).function(x)
except:
 _st_.goboom(_sage_const_67 )
_st_.blockend()
try:
 _st_.inline(_sage_const_3 , latex(f(x)))
except:
 _st_.goboom(_sage_const_74 )
try:
 _st_.inline(_sage_const_4 , latex(diff(f, x, _sage_const_2 )(x)))
except:
 _st_.goboom(_sage_const_74 )
try:
 _st_.inline(_sage_const_3 , latex(f(x)))
except:
 _st_.goboom(_sage_const_74 )
try:
 _st_.inline(_sage_const_4 , latex(diff(f, x, _sage_const_2 )(x)))
except:
 _st_.goboom(_sage_const_74 )
_st_.endofdoc()
